<?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('imu');
            
    $notifica     = $this->notifica;
    
    echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta name="robots" content="noindex" />
        <?php echo $this->render('partials/head.phtml'); ?>
       
        <script type="text/javascript">
             $(document).ready(function(){
                  
                 /*
                  * nascondo i campi 
                  */
                 var label_lotto_saturo = $('#lotto_saturo-label');                 
                 var id_lotto_saturo    = $('#lotto_saturo-element');
                 
                 var label_cepp = $('#capacita_edificatoria-label');                 
                 var id_cepp    = $('#capacita_edificatoria-element');                 

                 label_lotto_saturo.hide();
                 id_lotto_saturo.hide(); 

                 label_cepp.hide();
                 id_cepp.hide();
                 
                 
                 /*
                  * on area urbanizzata change
                  */
                 var radioSel = $("#calcolo_imu_lonato input[name=area_urbanizzata]"); 
                 radioSel.change(function onSelectChange(){
                    var selected = $("#calcolo_imu_lonato input[name=area_urbanizzata]:checked").val();  
                    if(selected == 1){
                        selModalitaIntervento(1);                        
                        label_lotto_saturo.show();
                        id_lotto_saturo.show();
                    }else if(selected == 0){
                        selModalitaIntervento(0); 
                        label_lotto_saturo.hide();                        
                        id_lotto_saturo.hide();                        
                    }
                 });
  
            });
        </script>        

    </head>
    <body>
    <?=$this->render('partials/header.phtml'); ?>
        <div id="content"> 
            <div class="notifica"><?=$notifica?></div>            
            <?php if ($this->escape($this->title))
                echo "<h2>" . $this->escape($this->title) . "</h2>";
            ?>
            <?=$this->layout()->content; ?>
        </div>
    <?=$this->render('partials/footer.phtml'); ?>
        
    <div id="debug" style="font-size: 10px; margin-top: 20px; color:#999;"></div>
    
    </body>
</html>