<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Default Application</title>
</head>
<body>
    <div id="content-errore">
  <h1>Ops, è successo un errore</h1>
  <h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>

  <h3>Informazioni sull'errore:</h3>
  <p>
      <b>Messaggio:</b> <?php echo $this->exception->getMessage() ?>
  </p>
  
  <!-- bottone ricalcola -->
  <?php $session = new Zend_Session_Namespace('step1'); // prendo i dati dalla sessione ?>
  <a id="button-ricalcola-errore" class="button doc-button left" href="<?= $this->url(array('controller' => $session->comune, 'action' => 'index'), null, TRUE);  ?>">Ricalcola</a>    

    </div>
  <div id="errore-sotto">
  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
  <?php endif ?>
  </div>
</body>
</html>
