<div id="privacy">
<h3>Privacy</h3>
<p>
    I dati forniti dagli utenti che utilizzano il software Wimu e i suoi servizi
    saranno registrati su database elettronici di propriet&agrave; di Wimu,
    che &egrave; titolare per il trattamento degli stessi.
    I dati personali degli utenti saranno utilizzati da Wimu nel rispetto delle norme
    di protezione dei dati personali stabilite dal Decreto Legislativo n. 196 del 30 giugno 2003 e
    dalle altre norme collegate vigenti in materia.
</p>
<p>
    La presente informativa riguarda sia i dati personali inviati al momento
    della registrazione/richiesta del documento sia qualsiasi altro dato inviato in seguito
    all'utilizzo del servizio oltre a quelli ricavati dalle visite e navigazioni nel sito.
</p>
<p>
    I dati richiesti sono obbligatori. Il conferimento dei dati obbligatori ed il trattamento che ne consegue
    per le finalit&agrave; sopra indicate sono funzionali all'esecuzione dei servizi.
    Il rifiuto del' Utente a fornire tali dati o il rifiuto di consentire al loro trattamento
    comporta l'impossibilit&agrave; di usufruire del servizio offerto da Wimu.
</p>
<p>
    Wimu utilizza i dati personali degli Utenti secondo tutte le operazioni
    di trattamento individuate dal D. lgs 196/2003 con modalit&agrave; automatizzate
    ed informatizzate - dette operazioni consistono nella raccolta, registrazione, organizzazione, conservazione,
    elaborazione, modifica, selezione, estrazione, raffronto, utilizzo, interconnessione
    ed tutte le altre operazioni utili alla fornitura dei servizi richiestici,
    compresa la comunicazione a terzi, se necessaria. I dati potranno anche essere
    organizzati in banche dati o archivi.<br/>
    Il trattamento dei dati personali &egrave; finalizzato a:<br/>
    - la fornitura dei servizi richiesti e la verifica della qualit&agrave; degli stessi;<br/>
    - il provvedimento degli eventuali adempimenti contabili e fiscali;<br/>
    - la verifica di eventuali illeciti (e il rintracciamento degli eventuali autori)
    in caso di specifiche richieste e per conto delle autorit&agrave; competenti;<br/>
    - la fornitura di informazioni e/o offerte su prodotti, servizi o iniziative
    offerti o promossi da Wimu e/o da partners commerciali e/o clienti e fornitori terzi, 
    senza che ci&ograve; determini la cessione dei dati personali a soggetti terzi;<br/></p>
<p>
    L'utente potr&agrave; accedere ai propri dati in qualsiasi momento ed
    esercitare i diritti di cui all'art. 7, D. lgs . 196/2003.
</p>
<p>
    Wimu comunica che, ai sensi dell'art. 7 della D. lgs . 196/2003:<br/>
    l' Utente ha diritto di ottenere la conferma dell'esistenza o meno di dati personali
    che lo riguardano e la loro comunicazione in forma intelligibile.<br/>
    L' Utente ha diritto di ottenere l'indicazione:<br/>
    a) dell'origine dei dati personali;<br/>
    b) delle finalit&agrave; e modalit&ograve; del trattamento;<br/>
    c) della logica applicata in caso di trattamento effettuato con l'ausilio di strumenti elettronici;<br/>
    d) degli estremi identificativi del titolare, dei responsabili e del rappresentante
    designato ai sensi dell'articolo 5, comma 2;<br/>
    e) dei soggetti o delle categorie di soggetti ai quali i dati personali possono
    essere comunicati o che possono venirne a conoscenza in qualit&agrave; di rappresentante
    designato nel territorio dello Stato, di responsabili o incaricati.
</p>
<p>
    L' Utente ha diritto di ottenere:<br/>
    a) l'aggiornamento, la rettificazione ovvero, quando vi ha interesse, l'integrazione dei dati;<br/>
    b) la cancellazione, la trasformazione in forma anonima o il blocco dei dati trattati in violazione
    di legge, compresi quelli di cui non &egrave; necessaria la conservazione in relazione agli scopi per i quali i dati sono stati raccolti o successivamente trattati;<br/>
    c) l'attestazione che le operazioni di cui alle lettere a) e b) sono state portate a conoscenza,
    anche per quanto riguarda il loro contenuto, di coloro ai quali i dati sono stati comunicati
    o diffusi, eccettuato il caso in cui tale adempimento si rivela impossibile o comporta un
    impiego di mezzi manifestamente sproporzionato rispetto al diritto tutelato.
</p>
<p>
    l' Utente ha diritto di opporsi, in tutto o in parte:<br/>
    a) per motivi legittimi al trattamento dei dati personali che lo riguardano,
    ancorch&egrave; pertinenti allo scopo della raccolta;<br/>
    b) al trattamento di dati personali che lo riguardano a fini di invio di materiale
    pubblicitario o di vendita diretta o per il compimento di ricerche di mercato o di comunicazione commerciale.<br/>
</p>
<p>
    L'eliminazione dei dati personali avviene semplicemente inviando in qualsiasi
    momento il codice fiscale dell'Utente che si vuole eliminare dai nostri database
    all'indirizzo di posta di wimu: 
    Una e-mail di conferma eliminazione sar&ograve; inviata non appena la procedura
    di cancellazione di tutti i dati relativa sar&agrave; avvenuta con successo.
</p>
<h3>Policy</h3>
<p>
    Premessa:<br/>questa pagina contiene informazioni sulla propriet&agrave;
    e il copyright, le cui condizioni vanno osservate e seguite.
    Tutti i marchi registrati appartengono ai legittimi proprietari.
    Nessuna parte di questo sito pu&ograve; essere riprodotta o copiata,
    salvo diverse indicazioni esplicite.<br/>
    Quando accedete a un sito Web esterno da wimu, ricordate che esso &egrave;
    indipendente da wimu e che quest'ultimo non ha alcun controllo sul contenuto
    del sito in questione. Inoltre, l'esistenza di un collegamento ipertestuale (link)
    verso un sito esterno non comporta l'approvazione o un'accettazione di responsabilit&agrave;
    da parte di Wimu circa il contenuto o l'utilizzazione di detto sito.</p>
    La registrazione e la consultazione del Sito sono si gratuite,
    e tuttavia sono soggette all'accettazione incondizionata da parte dell'Utente
    del presente Regolamento Generale e delle Condizioni d'Uso e delle relative
    Premesse: nel caso in cui l'Utente non sia in accordo con una qualsiasi delle
    clausole esposte in questo Regolamento, deve interrompere immediatamente
    l'utilizzo dei servizi di Wimu ed abbandonare la navigazione del sito.
<p>
    Durante l'uso dei servizi, l'Utente s'impegna in particolare a:<br/>
    - Non usare Wimu a fini professionali o commerciali (ricerca di clienti, adescamento).<br/>
    - Non pubblicare e/o diffondere in forma qualsiasi, informazioni o contenuti che abbiano
    l'effetto di diminuire, disorganizzare, impedire l'uso normale dei servizi,
    interrompere e/o rallentare la circolazione normale delle comunicazioni tra gli
    Iscritti mediante i servizi, come applicazioni, virus, cavalli di troia,
    invio di messaggi in massa (spam), ecc.
</p>
<p>
    Richiesta del documento per il calcolo del valore dell'area edificabile:<br/>
    Regole:<br/>
    - Non &egrave; possibile utilizzare i servizi di Wimu  per inviare spam nella rete.
    Rientra nella categoria dello spamming anche la dissimulazione dell'origine delle informazioni
    inviate o l'inserimento di informazioni false (nome, cognome e codice fiscale).
    Questi comportamenti rappresentano una grave violazione dell'etichetta di comportamento in rete.<br/>
    - Wimu  non consente lo svolgimento di attivit&agrave; illegali.<br/>
    - Oltre a rispettare questo Codice di comportamento, siete tenuti a non violare le leggi locali e nazionali vigenti nel paese dove vi trovate.
</p>
<p>
    Modifiche al servizio:<br/>
    Wimu si riserva in ogni tempo il diritto di modificare o disattivare,
    temporaneamente o permanentemente il Servizio (o una qualunque sua parte),
    con o senza comunicazione all'Utente. L'Utente conviene e concorda che Wimu
    non potr&agrave; in alcun modo essere ritenuta responsabile verso l'Utente stesso
    o verso terzi soggetti per la modifica, la sospensione o la disattivazione del Servizio.
</p>
<p>
    Manleva:<br/>
    Accettando il presente accordo, l'Utente si impegna a tenere indenne il Gestore
    nonch&egrave; gli amministratori, i collaboratori e i dipendenti della stessa
    da qualsiasi obbligo risarcitorio, comprese le spese legali, che possano essere
    richieste da terzi a causa della sua condotta su questo Sito ed ogni suo servizio,
    a causa della violazione del presente regolamento o a causa di ogni altra violazione
    di leggi, regolamenti o consuetudini.
</p>
<p>
    Responsabilit&agrave; e garanzia:<br/>
    I dati forniti da un Utente a Wimu devono essere corretti e
    conformi alla realt&agrave;. Wimu non pu&ograve; essere considerato
    responsabile della correttezza o dell'imprecisione delle informazioni e dei
    contenuti forniti dai visitatori del sito. Nel caso in cui Wimu venga considerato 
    responsabile di una violazione commessa, da parte di un Utente, degli obblighi che derivano ai sensi della legge vigente o
    delle presenti condizioni d'uso, l'Utente si impegna a garantire Wimu contro
    qualsiasi condanna pronunciata nei suoi confronti. Tale garanzia copre le indennit&agrave;
    che dovranno eventualmente essere versate, gli onorari degli avvocati e le spese legali
    che verranno addebitate a Wimu.
</p>
</div>