<?php
$session = new Zend_Session_Namespace('step1');


$values = $this->values;

$lonato_u_destammesse = Factory_dbTable::getClass("lonato", "u_destammesse");
$stmt5 = $lonato_u_destammesse->filtroDestinazioniAmmesse($values['id_m_ambiti']);
?>

<div id="risultati_calcolo_stima">
    
<!-- stima -->
<table id="risultati" class="left">
    <tr class="header-tabella1">
        <td>Capacità edificatoria calcolata</td>
        <td><?= $session->capacitaEdificatoria; ?></td>
        <td>(m3)</td>
    </tr>
    <tr class="">
        <td>Valore area calcolata</td>
        <td><?= $session->stimaUnitaria ?></td> 
        <td>(Euro/m3)</td>        
    </tr>
    <tr class="header-tabella1">
        <td>Valore area edificabile</td>
        <td><?= $session->valoraAreaEdificabile; ?></td> 
        <td>(Euro/m3)</td>        
    </tr>    
</table>
    <!-- indici -->
    <table id="indici" class="right">
        <tr class="header-tabella1">
            <td>Incidenza viabilità</td>
            <td>0,3</td> 
            <td></td>
        </tr>
        <tr class="">
            <td>Capacità edific. pred. o prees.</td>
            <td>0,3</td>
            <td></td>
        </tr>        
        <tr class="header-tabella1">
            <td>Indice fondario</td>
            <td>0,3</td> 
            <td>(volume in m3/m2)</td>
        </tr>
        <tr>
            <td>Incremento lotti saturi</td>
            <td>45</td>
            <td>(% di volume da indice)</td>
        </tr>    
        <tr class="header-tabella1">
            <td>Indice territoriale</td>
            <td>0,5</td>
            <td>(volume in m3/m2)</td>
        </tr>
        <tr>
            <td>Volume preesistente</td>
            <td>150</td>
            <td>(volume in m3)</td>
        </tr>
        <tr class="header-tabella1">
            <td>Volume incremento</td>
            <td>30</td>
            <td>(volume in m3)</td>
        </tr>
        <tr>
            <td>Volume predefinito</td>
            <td>50</td>  
            <td>(volume in m3)</td>
        </tr>
        <tr class="header-tabella1">
            <td>Indice fondario aggiuntivo</td>
            <td>0.6</td>
            <td>(volume in m3/m2)</td>
        </tr>    
    </table>
</div> 
<div>
<?= $this->form ?>
<a id="button-ricalcola-anagrafe" class="button doc-button" href="<?=
$this->url(array('controller' => 'Lonatodelgarda',
    'action' => 'index'), null, TRUE);?>">Ricalcola</a>
</div>
<div style="clear:both"></div>




