<?php
$session = new Zend_Session_Namespace('step1');


$values = $this->values;

$lonato_u_destammesse = Factory_dbTable::getClass("017092", "u_destammesse");
$stmt5 = $lonato_u_destammesse->filtroDestinazioniAmmesse($values['id_m_ambiti'],$session->data_calcolo);
?>

<div id="risultati_calcolo_stima">
    <!-- riassunto step1 -->
    <?= $session->riassunto_step1; ?> 
    <!-- indici mambiti tabella -->   
    <?= $session->indici_mambiti_stampa; ?>
    <!-- indici sambiti tabella -->
    <?= $session->indici_sambiti_stampa; ?>

</div> 
<div style="clear:both;"></div>
<div id="form-anagrafe">
    <h4 style ='font: small/1.5 "Tahoma", "Bitstream Vera" ; margin-left: 5px; text-align: left; font-size: 120% ;padding: 0px 0px 0px 0px; color: rgb(102, 102, 102);'>Inserisci i tuoi dati per stampare il documento</h4>
    <?=$this->form ?>
    <a id="button-ricalcola-anagrafe" class="button doc-button" href="<?=
    $this->url(array('controller' => $session->comune,
        'action' => 'index'), null, TRUE);
    ?>">Ricalcola</a>
    <a id="stampa" class="button doc-button" href="#">Stampa</a>    
    
</div>
<!-- stima -->
<table id="risultati-anagrafe">
    <caption>Risultato stimato</caption>      
    <tr class="header-tabella1">
        <td>Capacità edificatoria calcolata</td>
        <td><?= $session->capacitaEdificatoria; ?></td>
        <td>(m3)</td>
    </tr>
    <tr class="">
        <td>Valore area calcolata</td>
        <td><?= $session->stimaUnitaria ?></td> 
        <td>(Euro/m3)</td>        
    </tr>
    <tr class="header-tabella1">
        <td>Valore area edificabile</td>
        <td><?= $session->valoreAreaEdificabile; ?></td> 
        <td>(Euro/m3)</td>        
    </tr>    
</table>
<div style="clear:both"></div>
    <script type="text/javascript">
        $(function()
        {
                        
            $("#stampa").click(function(){
                doValidation();                
            });                   
                       
            function doValidation(){

                var url = '/public/Ajax/validate-anagrafe';
                
                var data = {};
                $('input').each(function(){
                    data[$(this).attr('name')] = $(this).val();                    
                });
                
                $.post(url,data,function(resp){
                      console.log(data);
                      console.log(resp);
                      if (resp.valid==true){
                        window.open("/public/Lonatodelgarda/stampa","_blank");
                        }else {
                            $('input').each(function(){
                                console.log(this);
                                var formElementId = ($(this).parent().prev().find('label').attr('for'));                
                                $("#"+formElementId).parent().find(".errors").remove();    
                                $("#"+formElementId).parent().append(getErrorHtml(resp[formElementId],formElementId));                                
                                //data[$(this).attr('name')] = $(this).val();                    
                            });                           
                            
 
                            
                        }
                        
                        
                    
                },'json');
                 
            }
            
            function getErrorHtml(formsError, id){
                var o = '<ul id="errors-'+id+'" class="errors">';
                for(errorKeys in formsError)
                {
                    o += '<li>'+formsError[errorKeys]+'</li>';
                }
                o += '</ul>';
                return o;
            }            
            
                                    
        });
    </script>




