<?
    $this->headTitle("Calcolo imu lonato");
    echo $this->form;
?>
<script type="text/javascript">
$(function()
{
    $("#capacita_edificatoria").blur(function(){
        //alert($(this).parent().prev().find('label').attr('for'));
        var id = $(this);
        if(id.val()==''){
           $("#submit").attr("disabled", "true");
        }else {
           $("#submit").removeAttr("disabled");
        }
        
        doValidation(id);
               
        });
      

    function doValidation(id){
        var url = '/public/Lonatodelgarda/validate-form';
        var data = {};
        data[id.attr('name')] = id.val();

        $.post(url,data,function(resp){

            var id2 = id.attr('name');
            $("#"+id2).parent().find("ul").remove();            
            $("#"+id2).after(getErrorHtml(resp[id2],id2));
            //getErrorHtml(resp[id2]),id2
            
        },'json');
    }

    function getErrorHtml(formsError, id){
        var o = '<ul id="errors-'+id+'" class="errors">';
        for(errorKeys in formsError)
        {
            o += '<li>'+formsError[errorKeys]+'</li>';
        }
        o += '</ul>';
        return o;
    }
    
    
});
</script>

