<div id="contenitore-index-data">
    <h4 style ='font: small/1.5 "Tahoma", "Bitstream Vera" ; text-align: left; font-size: 120% ;padding: 0px 0px 0px 0px; color: rgb(102, 102, 102);'>Compila i campi sottostanti e premi il pulsante: "continua il calcolo".</h4>    
<?
    $this->headTitle("Calcolo imu lonato");
    echo $this->form;
    
    $help = $this->help;

?>
<small>* campi obbligatori</small>
</div>
<div id="avvertenze">
<p><b>Avvertenze generali</b></p>
<?=$help->descrizione;?>
</div>
<div style="clear: both"></div>

