<?
    setlocale(LC_MONETARY, 'it_IT');
    $title = "Documento: Verbale di contestazione";

    $step1   = $this->values;
    $anagrafe = $this->anagrafe;

    require_once APPLICATION_PATH . '/../library/tcpdf/config/lang/ita.php';
    require_once APPLICATION_PATH . '/../library/tcpdf/tcpdf.php';     
    require_once APPLICATION_PATH . '/models/Utility.php'; 
    $utility_handle = new Utility();
     
    /*
     * inseriamo nella session il nome del comune
     * in modo da rendere il tutto dinamico
     */
    $comune = 'Lonato del Garda';
    
    //data della creazione di questo documento
    $timestamp = time();
    $today = mktime(date("H", $timestamp), date("i", $timestamp), date("s", $timestamp), date("m", $timestamp), date("d", $timestamp), date("Y", $timestamp));
    $today = date("Y-m-d H:i:s", $today);
    $data = $utility_handle->formattaDataOra($today);
    
    /*
     * dati relativi all'anagrafe
     */
    $nome    = $anagrafe['nome'];
    $cognome = $anagrafe['cognome'];
    $cf      = $anagrafe['cf'];
    
    /*
     * dati relativi al documento
     */
    $macro_ambito            = 'Nuclei di Antica Formazione (NAF vedansi gli specifici elaborati d\'analisi e normativi)';
    $sub_ambito              = 'Tutti gli ambiti';
    $zona                    = 'Barcuzzi';
    $area_urbanizzata        = 'No';
    $modalita_intervento     = 'Piano attuativo';
    $lotto_saturo            = 'Si';
    $superficie_territoriale = '1000';
    $capacita_edificatoria   = '500';
    
    /*
     * destinazioni ammesse
     */
    $lonato_u_destammesse = Factory_dbTable::getClass("017092", "u_destammesse");        
    $stmt5 = $lonato_u_destammesse->filtroDestinazioniAmmesse(2);
    
    
    /*
     * risultati del calcolo
     */
    $capacita_edificatoria_calcolata = 2000;
    $valore_area_calcolata           = 196;
    $valore_area_edificabile         = 1000;    
    
    /*
     * unità di misura
     */
    $u_capacita_edificatoria_calcolata = '';
    $u_valore_area_calcolata           = '';  
    
    $lonato_u_sambiti = Factory_dbTable::getClass("017092", "u_sambiti");
    $result = $lonato_u_sambiti->getVolumetria(intval($step1['id_u_sambiti']));
    $etichetta = $result[0]->indice_calcolo_capacita_edificatoria;

    if ($etichetta == "V3"){

        $u_capacita_edificatoria_calcolata = 'm3';
        $u_valore_area_calcolata = 'Euro/m3';

    }else {

        switch ($etichetta) {        

            case "V1": 
                $u_capacita_edificatoria_calcolata = 'm3';
                $u_valore_area_calcolata = 'Euro/m3';
            break;
            case "V2": 
                $u_capacita_edificatoria_calcolata = 'm3';
                $u_valore_area_calcolata = 'Euro/m3';
            break;
            case "V4": 
                $u_capacita_edificatoria_calcolata = 'm3';
                $u_valore_area_calcolata = 'Euro/m3';
            break;
            case "U1": 
                $u_capacita_edificatoria_calcolata = 'm2spl';
                $u_valore_area_calcolata = 'Euro/m2spl';
            break;
            case "U2": 
                $u_capacita_edificatoria_calcolata = 'm2spl';
                $u_valore_area_calcolata = 'Euro/m2spl';
            break;
            case "U4": 
                $u_capacita_edificatoria_calcolata = 'm2spl';
                $u_valore_area_calcolata = 'Euro/m2spl';
            break;
        }
    }    
    
        
    //-------------------------------------
    /*
     * inidici macro ambiti 
     */
    $contributo_compensativo_aggiuntivo = '';
    $valore_comprensativo_unitario      = '';
    $standard_pubblico_qualita          = '';
    
    /*
     * indici subambiti
     */
    $incidenza_viabilita        = 0.3;
    $cepp                       = 0.3;
    $indice_fondario            = 0.3;
    $incremento_lotti_saturi    = 45;
    $indice_fondario_aggiuntivo = 0.7;
    $volume_predefinito         = 1500;
    $volume_incremento          = 30;
    $volume_preesistente        = 30;
    $indice_territoriale        = 0.5;
 
    //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    
    //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    
    //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    
    //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    //
    //NON MODIFICARE DA QUI IN POI
    //
    //
    //--------------------------------------------------------------------------
    
class MYPDF extends TCPDF {

    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-20);
        // Set font
        $this->SetFont('helvetica', 'I', 11);

            
$tbl=<<<EOD
<hr style="background-color: #000;" />    
<table style="font-size: 25px;" class="left" width="100%" border="0" color="#000" cellspacing="0" cellpadding="2">
    <tr>
        <td>&copy; 2012 | documento creato con ...</td>
    </tr>
</table>
EOD;
        $this->writeHTML($tbl, true, false, false, false, '');

        // Page number
        //$this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }

}   
    
    $pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    // remove default header/footer
    $pdf->setPrintHeader(false);
    //PDF_MARGIN_TOP
    $pdf->SetFooterMargin(0);
    //set auto page breaks
    //$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
    $pdf->SetAutoPageBreak(TRUE, 0);
    // set border width
    //$pdf->SetLineWidth(0.508);
    //$pdf->setCellHeightRatio(1);
    // set color for cell border
    $pdf->SetDrawColor(0, 128, 255);
    //set image scale factor
    $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
    $pdf->AddPage();
    $pdf->SetFont('helvetica', '', 8);    
    
$tbl = <<<EOD
<style>
*{
    font-size: 30px;
}
.small {
    font-size: 20px;
}
.no-marpad{
    margin: 0px;
    padding: 0px;    
}

.f-left{
    float: left;
}
.f-right{
    float: right;
}

.left {
    text-align: left;
    /*date e numero alto a sx e sotto il resto*/
}
.right{
    text-align: right;
}
.center{
    text-align: center;
}

.table-header{
    border: 1px solid black;
}
.table-content{
    border: 1px solid black;
}
.table-footer{
    border: 1px solid black;
}
hr {
    color: #000;
    backgroud-color: #000;
}
h1 {
    font-size: 40px;
}
</style>
EOD;

//testata
$tbl .= <<<EOD
<table class="no-marpad" color="#000" cellspacing="0">
    <tr>
        <td><span class="left">$nome $cognome</span></td>
        <td><span style="text-align: center;" class="left">$comune</span></td>
        <td><span class="right f-right">$data</span></td>
    </tr>
</table>
<span class="left">$cf</span>
<br /><hr /><br />
EOD;
$pdf->writeHTML($tbl, true, false, false, false, '');

//riassunto dati
$tbl_riassunto = <<<EOD
<h1>Riassunto dei dati inseriti</h1>
<table style="font-size: 40px;">
    <tr>
        <td>Macro ambito</td>
        <td>$macro_ambito </td>        
    </tr>
     <tr>
        <td>Sub ambito</td>
        <td>$sub_ambito</td>        
    </tr>
    <tr>
        <td>Zona</td>
        <td>$zona</td>        
    </tr>
    <tr>
        <td>Area urbanizzata</td>
        <td>$area_urbanizzata</td>        
    </tr>
    <tr>
        <td>Modalita intervento</td>
        <td>$modalita_intervento</td>        
    </tr>  
    <tr>
        <td>Lotto_saturo</td>
        <td>$lotto_saturo</td>        
    </tr>  
    <tr>
        <td>Superficie territoriale</td>
        <td>$superficie_territoriale</td>        
    </tr>  
    <tr>
        <td>Capacita edificatoria</td>
        <td>$capacita_edificatoria</td>        
    </tr>      
</table>
EOD;
$pdf->writeHTML($tbl_riassunto, true, false, false, false, '');

//destinazioni
$tbl_destinazioni = '<table style="font-size: 40px;">';
$tbl_destinazioni .= '<tr><td>Destinazioni ammesse</td><td>Quota di progetto massima</td><td>Soglia dimensionale massima</td><td>Peso standard della destinazione</td><td>Quota di progetto inserita</td></tr>';

foreach ($stmt5 as $value) {
            $label = $value->descrizione;
            $id    = $value->id_u_destammesse;            
    
            $tbl_destinazioni .= '<tr>';             
            $tbl_destinazioni .= '<td>'.$value->quota_massima_ammissibile.'</td>';
            $tbl_destinazioni .= '<td>'.$value->soglia_dimensione_massima.'</td>';
            $tbl_destinazioni .= '<td>'.$value->quota_percentuale.'</td>';
            $tbl_destinazioni .= '<td>'.'0.4'.'</td>';            
            $tbl_destinazioni .= '</tr>';
        }
$tbl_destinazioni .= '</table>';        
$pdf->writeHTML($tbl_destinazioni, true, false, false, false, '');



//indici macro
$tbl_risultati = <<<EOD
<h1>Indici relativi ai macro ambiti</h1>
<table style="font-size: 40px;">
        <tr class="odd">
            <td>Contributo compensativo aggiuntivo</td>
            <td>$contributo_compensativo_aggiuntivo</td> 
            <td></td>
        </tr>
        <tr>
            <td>Valore comprensativo unitario</td>
            <td>$valore_comprensativo_unitario</td> 
            <td></td>
        </tr>
        <tr class="odd">
            <td>Standard pubblico qualit&agrave;</td>
            <td>$standard_pubblico_qualita</td>
            <td></td>
        </tr>
</table>
EOD;
$pdf->writeHTML($tbl_risultati, true, false, false, false, '');

//indici sub
$tbl_indici = <<<EOD
<h1>Indici relativi ai subambiti</h1>
<table style="font-size: 40px;">
        <tr class="odd">
            <td>Incidenza viabilità</td>
            <td>$incidenza_viabilita</td>
            <td></td>            
        </tr>
        <tr class="">
            <td>Capacità edific. pred. o prees.</td>
            <td>$cepp</td> 
            <td></td>
        </tr>        
        <tr class="odd">
            <td>Indice fondario</td>
            <td>$indice_fondario</td> 
            <td>(volume in m3/m2)</td>
        </tr>
        <tr>
            <td>Incremento lotti saturi</td>
            <td>$incremento_lotti_saturi</td> 
            <td>(% di volume da indice)</td>
        </tr>    
        <tr class="odd">
            <td>Indice territoriale</td>
            <td>$indice_territoriale</td>
            <td>(volume in m3/m2)</td>
        </tr>
        <tr>
            <td>Volume preesistente</td>
            <td>$volume_preesistente</td> 
            <td>(volume in m3)</td>
        </tr>
        <tr class="odd">
            <td>Volume incremento</td>
            <td>$volume_incremento</td> 
            <td>(volume in m3)</td>
        </tr>
        <tr>
            <td>Volume predefinito</td>
            <td>$volume_predefinito</td>
            <td>(volume in m3)</td>
        </tr>
        <tr class="odd">
            <td>Indice fondario aggiuntivo</td>
            <td>$indice_fondario_aggiuntivo</td>
            <td>(volume in m3/m2)</td>
        </tr>    
    </table>
EOD;
$pdf->writeHTML($tbl_indici, true, false, false, '');


//risultati
$tbl_risultati = <<<EOD
<h1>Valori stimati</h1>
<table style="font-size: 40px; background-color: #99CCFF;">
        <tr class="odd">
            <td>Capacità edificatoria calcolata</td>
            <td>$capacita_edificatoria_calcolata</td> 
            <td>$u_capacita_edificatoria_calcolata</td>
        </tr>
        <tr>
            <td>Valore area calcolata</td>
            <td>$valore_area_calcolata</td> 
            <td>$u_valore_area_calcolata</td>
        </tr>
        <tr class="odd">
            <td>Valore area edificabile</td>
            <td>$valore_area_edificabile</td>
            <td>Euro</td>
        </tr>
</table>
EOD;
$pdf->writeHTML($tbl_risultati, true, false, false, false, '');


ob_clean();
$pdf->Output('stima_imu_' . $comune . '_' . $cf . '.pdf', 'I');
?>

<!--<pre>
<?print_r($values)?>
</pre>
<pre>
<?print_r($anagrafe)?>
</pre>-->