<?php
// prelevo i dati 
$values = $this->values;
$capacita_edificatoria = $this->capacita_edificatoria;

$valore_area_calcolata = '';
$valore_area_edificabile = '';

$session = new Zend_Session_Namespace('step1'); // prendo i dati dalla sessione
$step1 = $session->step1;

$lonato_u_sambiti = Factory_dbTable::getClass("017092", "u_sambiti");
$result = $lonato_u_sambiti->getVolumetria(intval($step1['id_u_sambiti']),$session->data_calcolo);
$etichetta = $result[0]->indice_calcolo_capacita_edificatoria;

if (strtolower($etichetta) == "v3") {

    $u_capacita_edificatoria = 'm3';
    $u_valore_area_calcolata = 'Euro/m3';
} else {

    switch (strtolower($etichetta)) {

        case "v3":
            $u_capacita_edificatoria = 'm3';
            $u_valore_area_calcolata = 'Euro/m3';
            break;
        case "v1":
            $u_capacita_edificatoria = 'm3';
            $u_valore_area_calcolata = 'Euro/m3';
            break;
        case "v2":
            $u_capacita_edificatoria = 'm3';
            $u_valore_area_calcolata = 'Euro/m3';
            break;
        case "v4":
            $u_capacita_edificatoria = 'm3';
            $u_valore_area_calcolata = 'Euro/m3';
            break;
        case "u1":
            $u_capacita_edificatoria = 'm2spl';
            $u_valore_area_calcolata = 'Euro/m2spl';
            break;
        case "u2":
            $u_capacita_edificatoria = 'm2spl';
            $u_valore_area_calcolata = 'Euro/m2spl';
            break;
        case "u4":
            $u_capacita_edificatoria = 'm2spl';
            $u_valore_area_calcolata = 'Euro/m2spl';
            break;
        default:
            throw new Exception("Indice calcolo capacità edificatoria non valido.");
    }
}

$lonato_u_destammesse = Factory_dbTable::getClass("017092", "u_destammesse");
$lonato_u_cessioni = Factory_dbTable::getClass("017092", "u_cessioni");
$stmt5 = $lonato_u_destammesse->filtroDestinazioniAmmesse($values['id_m_ambiti'],$session->data_calcolo);

// prelevo i valori di stmt5 e li metto in dati_cessione
foreach ($stmt5 as $chiave => $valore) {
    $tabella_dati_cessione = $lonato_u_cessioni->getAll($step1["id_m_ambiti"], $valore["id_u_sdestinazioni"], $step1["id_u_modinterv"],$session->data_calcolo);
    foreach ($tabella_dati_cessione as $chiave2 => $valore2) {
        // debug echo $step1["id_m_ambiti"]. " ". $valore["id_u_sdestinazioni"] . "quota monetizzabile: ". $valore2->quota_monetizzabile . "chiave: " . $chiave2 . "<br/>";
        $dati_cessione[$chiave] = array("quota_monetizzabile" => $valore2->quota_monetizzabile,
            "quantita_cessione" => $valore2->quantita_cessione,
            "unita_misura_cessione" => $valore2->unita_misura_cessione);
    }
}

// header con titolo
$this->headTitle("Calcolo imu lonato");

// controllo se stmt5 ha almeno un valore, altrimenti errore
$vuoto = 1;
foreach ($stmt5 as $chiave => $valore) {
    if ($valore['descrizione']) {
        $vuoto = 0;
    }
}
// lancio exception
if ($vuoto == 0):
    ?>

    <div id="risultati_calcolo_stima">
        <!-- riassunto step1 -->
        <?= $session->riassunto_step1; ?> 
        <!-- indici mambiti tabella -->   
        <?= $session->indici_mambiti_stampa; ?>
        <!-- indici sambiti tabella -->
        <?= $session->indici_sambiti_stampa; ?>

    </div> 
<div style="clear:both"></div>
    <h4 style ='font: small/1.5 "Tahoma", "Bitstream Vera" ; text-align: left; font-size: 120% ;margin-left: 10px;padding: 0px 0px 0px 0px; color: rgb(102, 102, 102);'>Inserisci le quote di progetto</h4>
    <div id="div_form_2"> <!-- div con i dati form 2 -->
        <div class="left copri_tabella2 border_destra"> <!-- colonna1 -->
            <div id="header_destinazione_uso" class="border_sotto grigio">Destinazione d'uso ammessa</div>
            <div id="corpo_destinazione_uso">
                <?php foreach ($stmt5 as $chiave => $valore): ?>
                    <div class="blocco_tabella2"><?= $valore['descrizione'] ?></div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="left copri_tabella2 border_destra"> <!-- colonna2 -->
            <div id="header_quota_massima_ammissibile" class="border_sotto  grigio">Quota massima ammissibile</div>
            <div id="corpo_quota_massima_ammissibile" >
                <?php foreach ($stmt5 as $chiave => $valore): ?>
                    <div id="quota-<?= $valore["id_u_destammesse"] ?>" class="blocco_tabella2"><?= $valore['quota_massima_ammissibile'] ?></div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="left copri_tabella2 border_destra"> <!-- colonna3 -->
            <div id="header_soglia_dimensione_massima" class="border_sotto  grigio">Soglia dimensione massima</div>
            <div id="corpo_soglia_dimensione_massima">
                <?php foreach ($stmt5 as $chiave => $valore): ?>
                    <div class="blocco_tabella2"><?= $valore['soglia_dimensione_massima'] ?></div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="left copri_tabella2 border_destra"> <!-- colonna4 -->
            <div id="header_peso_standard" class="border_sotto  grigio">Peso standard</div>
            <div id="corpo_peso_standard">
                <?php foreach ($stmt5 as $chiave => $valore): ?>
                    <div class="blocco_tabella2"><?= $valore['quota_percentuale'] ?></div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="left copri_tabella2"> <!-- colonna5 -->
            <div id="header_quota_progetto" class="border_sotto grigio">Quota di progetto</div>
            <div id="corpo_quota_progetto">
                <?= $this->form; ?>
            </div>
        </div>
        <!-- se urbanizzata non ho cessioni -->
        <?php if (!$values["area_urbanizzata"]): ?>
            <div class="left copri_tabella2 border-sinistra border_destra"> <!-- colonna6 -->
                <div id="header-um-cessione" class="border_sotto grigio">U.m. Cessione</div>
                <div id="corpo-um-cessione">
                    <?php foreach ($dati_cessione as $chiave => $valore): ?>
                        <div class="blocco_tabella2"><?= $valore['unita_misura_cessione'] ?></div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>
        <!-- se urbanizzata non ho cessioni -->
        <?php if (!$values["area_urbanizzata"]): ?>
            <div class="left copri_tabella2 border_destra"> <!-- colonna7 -->
                <div id="header-cessione" class="border_sotto grigio">Quantità cessione</div>
                <div id="corpo-cessione">
                    <?php foreach ($dati_cessione as $chiave => $valore): ?>
                        <div class="blocco_tabella2"><?= $valore['quantita_cessione'] ?></div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>
        <!-- se urbanizzata non ho cessioni -->
        <?php if (!$values["area_urbanizzata"]): ?>
            <div class="left copri_tabella2"> <!-- colonna8 -->
                <div id="header-quota-monetaria" class="border_sotto grigio">Quota monetizzazione</div>
                <div id="corpo-quota-monetaria">
                    <?php foreach ($dati_cessione as $chiave => $valore): ?>
                        <div class="blocco_tabella2"><?= $valore['quota_monetizzabile'] ?></div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>

        <!-- bottone ricalcola -->
        <a id="button-ricalcola-form2" class="button doc-button" href="<?= $this->url(array('controller' => $session->comune, 'action' => 'index'), null, TRUE); ?>">Ricalcola</a>

    </div>

    <div style="color: red; font-size: 11px;" id="errore_somma" ></div>

    <!-- torna al form1 -->
    <div style="clear:both"></div>
    
    <!-- stima -->
    <table id="risultati" class="left">
    <caption>Risultato stimato</caption>    
    <tr class="header-tabella1">
            <td>Capacità edificatoria calcolata</td>
            <td><span id="v_capacita_edificatoria"><?= $capacita_edificatoria ?></span></td>
            <td><?= $u_capacita_edificatoria ?></td>
        </tr>
        <tr class="">
            <td>Valore area calcolata</td>
            <td><span id="v_valore_area_calcolata"><?= $valore_area_calcolata ?></span></td> 
            <td><?= $u_valore_area_calcolata ?></td>        
        </tr>
        <tr class="header-tabella1">
            <td>Valore area edificabile</td>
            <td><span id="v_valore_area_edificabile"><?= $valore_area_edificabile ?></span></td> 
            <td>Euro</td>        
        </tr>    
    </table>


    <script type="text/javascript">
        $(function()
        {
            
//        width: 30px;
            $("input[type=text]").css('width','30px');
            
            $("input").blur(function(){
                //
                var formElementId = ($(this).parent().prev().find('label').attr('for'));                
                doValidation(formElementId);
                                               
            });
                                      
            function doValidation(id){

                var url = '/public/Ajax/validate-form-step2';
                var url2 = '/public/Ajax/calcola-valore-stimato'; 
                var url3 = '/public/Ajax/verifica-quote';    
                
                var data = {};
                $('input').each(function(){
                    data[$(this).attr('name')] = $(this).val();
                    //alert($(this).val());
                });

                $.post(url,data,function(resp){

                    $("#"+id).parent().find(".errors").remove();    
                    $("#"+id).parent().append(getErrorHtml(resp[id],id));                     
                                         
                },'json');

                console.log(data);
                                                                        
                $.post(url2,data,function(resp){

                    console.log(resp);
                    $('#v_valore_area_calcolata').html(resp.valore_area_calcolata);
                    $('#v_valore_area_edificabile').html(resp.valore_area_edificabile);                    
                                         
                },'json');
                
                $.post(url3,data,function(resp){

                    console.log(resp);

                    //$("#errore_somma").remove(); 
                    if (resp.somma_quote){
                        $("#continua_stampa").removeAttr("disabled");
                        $("#errore_somma").html('');
                    }else {
                        $("#continua_stampa").attr("disabled", "true");
                        $("#errore_somma").html('La somma dei valori in ingresso non può essere maggiore di 1');
                    }                   
                },'json');                
                                                       
                                    
            }

            function getErrorHtml(formsError, id){
                var o = '<ul id="errors-'+id+'" class="errors">';
                for(errorKeys in formsError)
                {
                    o += '<li>'+formsError[errorKeys]+'</li>';
                }
                o += '</ul>';
                return o;
            }
                                    
                                    
        });
    </script>
<?php else: ?>
    <h2 style="text-align: center;">Attenzione: non si hanno sufficenti dati per effettuare il calcolo in questo sumambito.</h2>
<?php endif; ?>



