<?php
$values                = $this->values;
$capacita_edificatoria = $this->capacita_edificatoria;

$lonato_u_destammesse = Factory_dbTable::getClass("lonato", "u_destammesse");
$stmt5 = $lonato_u_destammesse->filtroDestinazioniAmmesse($values['id_m_ambiti']);
$this->headTitle("Calcolo imu lonato");
?>
<div id="risultati_calcolo_stima">
    
<!-- stima -->
<table id="risultati" class="left">
    <tr class="header-tabella1">
        <td>Capacità edificatoria calcolata</td>
        <td><?=$capacita_edificatoria?></td>
        <td>(m3)</td>
    </tr>
    <tr class="">
        <td>Valore area calcolata</td>
        <td>123</td> 
        <td>(Euro/m3)</td>        
    </tr>
    <tr class="header-tabella1">
        <td>Valore area edificabile</td>
        <td>69.000</td> 
        <td>(Euro/m3)</td>        
    </tr>    
</table>
    <!-- indici -->
    <table id="indici" class="right">
        <tr class="header-tabella1">
            <td>Incidenza viabilità</td>
            <td>0,3</td> 
            <td></td>
        </tr>
        <tr class="">
            <td>Capacità edific. pred. o prees.</td>
            <td>0,3</td>
            <td></td>
        </tr>        
        <tr class="header-tabella1">
            <td>Indice fondario</td>
            <td>0,3</td> 
            <td>(volume in m3/m2)</td>
        </tr>
        <tr>
            <td>Incremento lotti saturi</td>
            <td>45</td>
            <td>(% di volume da indice)</td>
        </tr>    
        <tr class="header-tabella1">
            <td>Indice territoriale</td>
            <td>0,5</td>
            <td>(volume in m3/m2)</td>
        </tr>
        <tr>
            <td>Volume preesistente</td>
            <td>150</td>
            <td>(volume in m3)</td>
        </tr>
        <tr class="header-tabella1">
            <td>Volume incremento</td>
            <td>30</td>
            <td>(volume in m3)</td>
        </tr>
        <tr>
            <td>Volume predefinito</td>
            <td>50</td>  
            <td>(volume in m3)</td>
        </tr>
        <tr class="header-tabella1">
            <td>Indice fondario aggiuntivo</td>
            <td>0.6</td>
            <td>(volume in m3/m2)</td>
        </tr>    
    </table>
</div> 
<div id="div_form_2" class=""> <!-- div con i dati form 2 -->
    <div class="left copri_tabella2 border_destra"> <!-- colonna1 -->
        <div id="header_destinazione_uso" class="border_sotto grigio">Destinazione d'uso ammessa</div>
        <div id="corpo_destinazione_uso">
            <?php foreach ($stmt5 as $chiave => $valore): ?>
                <div class="blocco_tabella2"><?= $valore['descrizione'] ?></div>
            <?php endforeach; ?>
        </div>
    </div>

    <div class="left copri_tabella2 border_destra"> <!-- colonna2 -->
        <div id="header_quota_massima_ammissibile" class="border_sotto  grigio">Quota massima ammissibile</div>
        <div id="corpo_quota_massima_ammissibile" >
            <?php foreach ($stmt5 as $chiave => $valore): ?>
                <div id="quota-<?= $valore["id_u_destammesse"] ?>" class="blocco_tabella2"><?= $valore['quota_massima_ammissibile'] ?></div>
            <?php endforeach; ?>
        </div>
    </div>

    <div class="left copri_tabella2 border_destra"> <!-- colonna3 -->
        <div id="header_soglia_dimensione_massima" class="border_sotto  grigio">Soglia dimensione massima</div>
        <div id="corpo_soglia_dimensione_massima">
            <?php foreach ($stmt5 as $chiave => $valore): ?>
                <div class="blocco_tabella2"><?= $valore['soglia_dimensione_massima'] ?></div>
            <?php endforeach; ?>
        </div>
    </div>

    <div class="left copri_tabella2 border_destra"> <!-- colonna4 -->
        <div id="header_peso_standard" class="border_sotto  grigio">Peso standard della destinazione</div>
        <div id="corpo_peso_standard">
            <?php foreach ($stmt5 as $chiave => $valore): ?>
                <div class="blocco_tabella2"><?= $valore['quota_percentuale'] ?></div>
            <?php endforeach; ?>
        </div>
    </div>

    <div class="left copri_tabella2"> <!-- colonna5 -->
        <div id="header_quota_progetto" class="border_sotto grigio">Quota di progetto</div>
        <div id="corpo_quota_progetto">
            <?= $this->form; ?>
            <a id="button-ricalcola" class="button doc-button min-larghezza" href="<?= $this->url(array('controller' => 'Lonatodelgarda','action' => 'index'), null, TRUE);?>">Ricalcola</a>
        </div>
    </div>
</div>
    <!-- torna al form1 -->
<div style="clear:both"></div>

<script type="text/javascript">
$(function()
{
    $("input").blur(function(){
        //
        var formElementId = ($(this).parent().prev().find('label').attr('for'));                
        doValidation(formElementId);
               
        });
      
    function doValidation(id){

        var url = '/public/Ajax/validate-form-step2';
        var data = {};
        $('input').each(function(){
            data[$(this).attr('name')] = $(this).val();
        });
        console.log(data);
        $.post(url,data,function(resp){

            $("#"+id).parent().find(".errors").remove();    
            $("#"+id).parent().append(getErrorHtml(resp[id],id));
            
        },'json');
    }

    function getErrorHtml(formsError, id){
        var o = '<ul id="errors-'+id+'" class="errors">';
        for(errorKeys in formsError)
        {
            o += '<li>'+formsError[errorKeys]+'</li>';
        }
        o += '</ul>';
        return o;
    }
    
    
});
</script>

